anirban/routes/web.php
<?php

use Illuminate\Support\Facades\Auth;

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();
Route::post('signin', 'Auth\SigninController@signin');
Route::post('signup', 'Auth\SignupController@signup');

Route::get('/home', 'HomeController@index')->name('home');

// Calendar
Route::get('calendar', 'CalendarController@index');

// Send SMS
Route::post('sms/sendsms', 'SendsmsController@sendsms');
Route::post('sms/sendlonesms', 'SendsmsController@sendlonesms');

// View User Only
Route::get('/dashboard/show/{account}', 'DashboardController@show')->name('dashboard.show');
Route::post('/dashboard/password', 'DashboardController@password')->name('dashboard.password');
Route::get('/dashboard', 'DashboardController@index')->name('dashboard');

// Member Route
Route::get('member/user/{user}', 'MemberController@active');
Route::post('member/profile/{profile}', 'MemberController@profile');
Route::resource('member', 'MemberController');

// Accounts Route
Route::get('account/lone/{account}', 'AccountController@active');
Route::resource('account', 'AccountController');

// Tasks Route
Route::get('task/user/{task}', 'TaskController@active');
Route::resource('task', 'TaskController');

// Others Route
Route::get('other/user/{other}', 'OtherController@active');
Route::resource('other', 'OtherController');

// Amounts Controller
Route::get('amount/details/{id}', 'AmountController@amountdetails');
Route::get('amount/daly/{account}', 'AmountController@amount');
Route::get('amount/saving/{account}', 'AmountController@saving');
Route::get('amount/dashboard', 'AmountController@dashboard');
Route::post('amount/daly', 'AmountController@dayamount');
Route::post('amount/transfer', 'AmountController@transfer');
Route::resource('amount', 'AmountController');

//Saving Route
Route::get('saving', 'SavingController@index');

// Lone Route
Route::get('lone', 'LoneController@index');
Route::get('lone/{id}', 'LoneController@show');
Route::post('lone/amount', 'LoneController@amount');
Route::post('lone/fixed', 'LoneController@fixed');

// Fixed Route
Route::get('fixed', 'FixedController@index');

// Role Route
Route::post('role/savepermission', 'RoleController@savepermission');
Route::get('role/add', 'RoleController@add');
Route::resource('role', 'RoleController');

// Permission Route
Route::resource('permission', 'PermissionController');

// Invoice Controller
Route::get('invoic/account-info/{account}', 'InvoiceController@accountinfo');
Route::get('invoic/account-info/print/{account}', 'InvoiceController@accountinfoprint');
Route::get('invoic/account-form/{account}', 'InvoiceController@accountform');

// Mobile
Route::get('/mobile/login', function () {
	if (Auth::check()) {
		return redirect('mobile/dashboard');
	} else {
    	return view('mobile.login');
	}
});
Route::get('mobile/dashboard', 'MobileController@dashboard');
Route::get('mobile/lone', 'MobileController@lone');
Route::get('mobile/saving', 'MobileController@saving');
Route::get('mobile/fixed', 'MobileController@fixed');
Route::get('mobile/show/{id}', 'MobileController@show');
Route::get('mobile/payment/{id}', 'MobileController@payment');
Route::post('mobile/login', 'MobileController@login');

anirban/app/Other.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Other extends Model
{
    //
}

anirban/app/Http/Controllers/OtherController.php
<?php

namespace App\Http\Controllers;

use App\Other;
use Illuminate\Http\Request;
use MercurySeries\Flashy\Flashy;

class OtherController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $others = Other::all();
        return view('other.index', compact('others'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('other.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'other_date' => 'required',
            'other_description' => 'required',
            'elevation_amount' => 'required',
            'saving_amount' => 'required',
        ]);

        $other = new Other;
        $other->other_date = $request->other_date;
        $other->other_description = $request->other_description;
        $other->elevation_amount = $request->elevation_amount;
        $other->saving_amount = $request->saving_amount;
        $other->save();
        Flashy::message('Success', 'http://your-awesome-link.com');
        return back();
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Other  $other
     * @return \Illuminate\Http\Response
     */
    public function show(Other $other)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Other  $other
     * @return \Illuminate\Http\Response
     */
    public function edit(Other $other)
    {
        return view('other.edit', compact('other'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Other  $other
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Other $other)
    {
        $request->validate([
            'other_date' => 'required',
            'other_description' => 'required',
            'elevation_amount' => 'required',
            'saving_amount' => 'required',
        ]);

        $other->other_date = $request->other_date;
        $other->other_description = $request->other_description;
        $other->elevation_amount = $request->elevation_amount;
        $other->saving_amount = $request->saving_amount;
        $other->save();
        Flashy::message('Success', 'http://your-awesome-link.com');
        return back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Other  $other
     * @return \Illuminate\Http\Response
     */
    public function destroy(Other $other)
    {
        $other->delete();
        Flashy::message('Success', 'http://your-awesome-link.com');
        return back();
    }
}

anirban/resources/views/other/create.blade.php
@extends('layouts.app')

@section('header-script')
<link rel="stylesheet" href={{ asset("admin/bower_components/bootstrap-daterangepicker/daterangepicker.css") }}>
<link rel="stylesheet" href={{ asset("admin/bower_components/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css") }}>
<link rel="stylesheet" href={{ asset("admin/bower_components/select2/dist/css/select2.min.css") }}>
@endsection

@section('title', 'অন‍্যান‍্য')
@section('content-title', 'অন‍্যান‍্য')
@section('content-subtitle', 'অন‍্যান‍্য খরচ ও জমা')
@section('link-list')
<li><a href="{{ route('home') }}"><i class="fa fa-dashboard"></i> ডেসবোর্ড</a></li>
<li ><a href="{{ route('other.index') }}">অন‍্যান‍্য খরচপাতি লিস্ট</a></li>
<li class="active"><a href="{{ route('other.create') }}">অন‍্যান‍্য খরচ ক্রিয়েট</a></li>
@endsection

@section('content')
@can('other.create', Auth::user())
<!-- Main content -->
<section class="content">

  <!-- Default box -->
  <div class="row">
    <div class="col-md-6">
      <div class="box box-primary">
        <div class="box-header with-border">
          <h3 class="box-title">অন‍্যান‍্য খরচ ও জমা ফরম</h3>
        </div>
        @include('layouts.message')
        <!-- /.box-header -->
        <!-- form start -->
        <form role="form" action="{{ route('other.store') }}" method="post">
          {{ csrf_field() }}
          <div class="box-body">

            <div class="form-group">
              <label for="name">তারিখ</label>
              <div class="input-group date">
                <div class="input-group-addon">
                  <i class="fa fa-calendar"></i>
                </div>
                <input type="text" class="form-control pull-right" id="datepicker" name="other_date" data-date-format="yyyy/mm/dd">
              </div>
            </div>

            <div class="form-group">
              <label>বিস্তারিত</label>
              <textarea type="text" class="form-control" id="contact_number" placeholder="Description" name="other_description">{{ old('other_description') }}</textarea>
            </div>

            <div class="form-group">
              <label for="elevation_amount">খরচ</label>
              <input class="form-control" id="elevation_amount" placeholder="Cost Amount" type="number" name="elevation_amount" value="{{ old('elevation_amount') }}">
            </div>

            <div class="form-group">
              <label for="saving_amount">জমা</label>
              <input class="form-control" id="saving_amount" placeholder="Saving Amount" type="number" name="saving_amount" value="{{ old('saving_amount') }}">
            </div>
            
          </div>
          <!-- /.box-body -->

          <div class="box-footer">
            <button type="submit" class="btn btn-primary">যুক্ত করুন</button>
          </div>
        </form>
      </div>
    </div>
    <div class="col-md-6">
      <div class="box box-primary">
        <div class="box-header with-border">
          <h3 class="box-title">ব‍্যবহার বিধি</h3>
        </div>
        <!-- /.box-header -->
        <!-- form start -->
          <div class="box-body">
            
          </div>
          <!-- /.box-body -->
          <div class="box-footer">
            
          </div>
      </div>
    </div>
  </div>
  <!-- /.box -->

</section>
<!-- /.content -->
@endcan
@endsection

@section('footer-script')
<script src={{ asset("admin/bower_components/moment/min/moment.min.js") }}></script>
<script src={{ asset("admin/bower_components/bootstrap-daterangepicker/daterangepicker.js") }}></script>
<!-- bootstrap datepicker -->
<script src={{ asset("admin/bower_components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js") }}></script>
<script src={{ asset("admin/bower_components/select2/dist/js/select2.full.min.js") }}></script>

<script>
  $(function () {

    //Date picker
    $('#datepicker').datepicker({
      autoclose: true
    })
    $('.select2').select2()
  })
</script>
@endsection

anirban/resources/views/other/edit.blade.php
@extends('layouts.app')

@section('header-script')
<link rel="stylesheet" href={{ asset("admin/bower_components/bootstrap-daterangepicker/daterangepicker.css") }}>
<link rel="stylesheet" href={{ asset("admin/bower_components/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css") }}>
<link rel="stylesheet" href={{ asset("admin/bower_components/select2/dist/css/select2.min.css") }}>
@endsection

@section('title', 'অন‍্যান‍্য')
@section('content-title', 'অন‍্যান‍্য')
@section('content-subtitle', 'অন‍্যান‍্য খরচ জমা পেজ')
@section('link-list')
<li><a href="{{ route('home') }}"><i class="fa fa-dashboard"></i> ডেসবোর্ড</a></li>
<li ><a href="{{ route('other.index') }}">অন‍্যান‍্য খরচ জমা লিস্ট</a></li>
<li class="active"><a href="{{ route('other.create') }}">অন‍্যান‍্য খরচ জমা তৈরি</a></li>
@endsection

@section('content')
@can('other.update', Auth::user())
<!-- Main content -->
<section class="content">

  <!-- Default box -->
  <div class="row">
    <div class="col-md-6">
      <div class="box box-primary">
        <div class="box-header with-border">
          <h3 class="box-title">অন‍্যান‍্য খরচ জমা সম্পাদন</h3>
        </div>
        @include('layouts.message')
        <!-- /.box-header -->
        <!-- form start -->
        <form role="form" action="{{ route('other.update', $other->id) }}" method="post">
          {{ csrf_field() }}
          {{ method_field('PATCH') }}
          <div class="box-body">

            <div class="form-group">
              <label for="name">তারিখ</label>
              <div class="input-group date">
                <div class="input-group-addon">
                  <i class="fa fa-calendar"></i>
                </div>
                <input type="text" class="form-control pull-right" id="datepicker" name="other_date" data-date-format="yyyy/mm/dd" value="{{ $other->other_date }}">
              </div>
            </div>

            <div class="form-group">
              <label>বিস্তারিত</label>
              <textarea type="text" class="form-control" id="contact_number" placeholder="Description" name="other_description">{{ $other->other_description }}</textarea>
            </div>

            <div class="form-group">
              <label for="elevation_amount">খরচ</label>
              <input class="form-control" id="elevation_amount" placeholder="Cost Amount" type="number" name="elevation_amount" value="{{ $other->elevation_amount }}">
            </div>

            <div class="form-group">
              <label for="saving_amount">জমা</label>
              <input class="form-control" id="saving_amount" placeholder="Saving Amount" type="number" name="saving_amount" value="{{ $other->saving_amount }}">
            </div>
            
          </div>
          <!-- /.box-body -->

          <div class="box-footer">
            <button type="submit" class="btn btn-primary">সম্পাদন করুন</button>
          </div>
        </form>
      </div>
    </div>
    <div class="col-md-6">
      <div class="box box-primary">
        <div class="box-header with-border">
          <h3 class="box-title">ব‍্যবহার বিধি</h3>
        </div>
        <!-- /.box-header -->
        <!-- form start -->
          <div class="box-body">
            
          </div>
          <!-- /.box-body -->
          <div class="box-footer">
            
          </div>
      </div>
    </div>
  </div>
  <!-- /.box -->

</section>
<!-- /.content -->
@endcan
@endsection

@section('footer-script')
<script src={{ asset("admin/bower_components/moment/min/moment.min.js") }}></script>
<script src={{ asset("admin/bower_components/bootstrap-daterangepicker/daterangepicker.js") }}></script>
<!-- bootstrap datepicker -->
<script src={{ asset("admin/bower_components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js") }}></script>
<script src={{ asset("admin/bower_components/select2/dist/js/select2.full.min.js") }}></script>

<script>
  $(function () {

    //Date picker
    $('#datepicker').datepicker({
      autoclose: true
    })
    $('.select2').select2()
  })
</script>
@endsection

anirban/resources/views/other/index.blade.php
@extends('layouts.app')

@section('title', 'অন‍্যান‍্য')
@section('content-title', 'অন‍্যান‍্য')
@section('content-subtitle', 'অন‍্যান‍্য জমা ও খরচ লিস্ট')
@section('link-list')
<li><a href="{{ route('home') }}"><i class="fa fa-dashboard"></i> ডেসবোর্ড</a></li>
<li class="active"><a href="{{ route('other.index') }}">অন‍্যান‍্য জমা ও খরচ লিস্ট</a></li>
@endsection

@section('header-script')
<link rel="stylesheet" href={{ asset("admin/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css") }}>
@endsection

@section('content')
@can('other.view', Auth::user())
<!-- Main content -->
<section class="content">

  <!-- Default box -->
  <div class="box">
    <div class="box-header">
      {{-- <h3 class="box-title">Data Table With Full Features</h3> --}}
    </div>
    <!-- /.box-header -->
    <div class="box-body">
      <table id="example1" class="table table-bordered table-striped">
        <thead>
          <tr>
            <th>তারিখ</th>
            <th>বিস্তারিত</th>
            <th>খরচ</th>
            <th>জমা</th>
            @can('other.update')
            <th></th>
            @endcan
          </tr>
        </thead>
        <tbody>
          @foreach($others as $other)
          <tr>
            <td>{{ \App\Classes\Helper::getDate($other->other_date) }}</td>
            <td>{{ $other->other_description }}</td>
            <td>{{ $other->elevation_amount }}</td>
            <td>{{ $other->saving_amount }}</td>
            @can('other.update')
            <td>
              <a href="{{ route('other.edit', $other->id) }}" class="btn btn-info btn-xs"><span class="fa fa-edit"></span></a>

              @can('other.delete')
              <form id="delete-form-{{ $other->id }}" method="post" action="{{ route('other.destroy',$other->id) }}" style="display: none">
                {{ csrf_field() }}
                {{ method_field('DELETE') }}
              </form>
              <a class="btn btn-danger btn-xs" href="" onclick="
              if(confirm('Are you sure, You Want to delete this?'))
                  {
                    event.preventDefault();
                    document.getElementById('delete-form-{{ $other->id }}').submit();
                  }
                  else{
                    event.preventDefault();
                  }" ><span class="fa fa-trash"></span></a>
               @endcan   
            </td>
            @endcan
          </tr>
          @endforeach
        </tbody>
        <tfoot>
          <tr>
            <th>তারিখ</th>
            <th>বিস্তারিত</th>
            <th>খরচ</th>
            <th>জমা</th>
            @can('other.update')
            <th></th>
            @endcan
          </tr>
        </tfoot>
      </table>
    </div>
    <!-- /.box-body -->
  </div>
  <!-- /.box -->

</section>
<!-- /.content -->
@endcan
@endsection

@section('footer-script')
<script src={{ asset("admin/bower_components/datatables.net/js/jquery.dataTables.min.js") }}></script>
<script src={{ asset("admin/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js") }}></script>
<script>
  $(function () {
    $('#example1').DataTable()
  })
</script>
@endsection