movie-tube/youtubemovie/routes/web.php
<?php

Route::get('/', 'HomeController@index');

Route::get('search/{slug}', 'SearchController@search');
Route::get('top-search', 'SearchController@searchtop')->name('searchTop');
Route::post('search-movie', 'SearchController@searchMovie');

Route::post('favorite/{id}', 'FavoriteController@favoriteVideo');
Route::post('unfavorite/{id}', 'FavoriteController@unFavoriteVideo');

Route::get('my_favorites', 'FavoriteController@myFavorites')->middleware('auth');

Route::get('login/facebook', 'Auth\LoginController@redirectToProvider');
Route::get('login/facebook/callback', 'Auth\LoginController@handleProviderCallback');
Route::resource('video', 'VideoController');
Route::resource('rate', 'RateController');

Auth::routes();

// Route::get('/home', 'HomeController@index')->name('home');

movie-tube/youtubemovie/app/Video.php
<?php

namespace App;

use App\Favorite;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Auth;

class Video extends Model
{
    public function rates()
    {
        return $this->hasMany('App\Rate');
    }

    public function favorited()
	{
	    return (bool) Favorite::where('user_id', Auth::id())
	                        ->where('video_id', $this->id)
	                        ->first();
	}
}

movie-tube/youtubemovie/app/Http/Controllers/VideoController.php
<?php

namespace App\Http\Controllers;

use App\Rate;
use App\Video;
use Auth;
use Illuminate\Http\Request;


class VideoController extends Controller
{
    public function __construct()
    {

        $this->middleware('auth')->except('index', 'show');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $videos = Video::inRandomOrder()->paginate(12);
        return view('welcome', compact('videos'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('video.create', compact('movielist'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'url' => 'required',
            'name' => 'required',
            'catagory' => 'required',
        ]);

        $video = new Video;
        $video->user_id = Auth::id();
        $video->url = 'https://www.youtube.com/embed/' . $request->url;
        $video->name = $request->name;
        $video->catagory =  $request->catagory;
        $video->description = $request->description;
        $video->save();

        return redirect('/');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Video  $video
     * @return \Illuminate\Http\Response
     */
    public function show(Video $video)
    {
        $rate = Rate::where([
                       'user_id' => Auth::id(),
                       'video_id' => $video->id,
                ])->first();
        $newmovies = Video::latest()->take(3)->get();
        $viewrelative = Video::where('catagory', $video->catagory)->inRandomOrder()->take(8)->get();
        $movielist = \App\Video::all();
        return view('video.show', compact('video', 'rate', 'newmovies', 'viewrelative', 'movielist'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Video  $video
     * @return \Illuminate\Http\Response
     */
    public function edit(Video $video)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Video  $video
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Video $video)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Video  $video
     * @return \Illuminate\Http\Response
     */
    public function destroy(Video $video)
    {
        //
    }
}

movie-tube/youtubemovie/resources/views/video/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
	<div class="row">
		<div class="col-md-6">
			<h6>নতুন মুভি যুক্ত করার ফরম</h6>
			<hr>
			<div class="video-form">
				<form action="{{ route('video.store') }}" method="post">
					{{ csrf_field() }}
				  <div class="form-group {{ $errors->has('url') ? ' has-error' : '' }}">
				    <label for="youTubeUrl">ইউটিউব ইউআরএল</label>
				    @if ($errors->has('url'))
                        <span class="help-block">
                            <strong style="color: red;">{{ $errors->first('url') }}</strong>
                        </span>
                    @endif
				    <div class="row">
				    <div class="col-md-7">
				    	<input type="text" class="form-control" id="youTubeUrl" placeholder="https://www.youtube.com/watch?v=" disabled>
				    </div>
				    <div class="col-md-5">
				   		<input type="text" name="url" class="form-control" id="youTubeUrl" placeholder="ইউটিউব ইউআরএল">
				    </div>
				    </div>
				  </div>
				  <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
				    <label for="youTubeName">মুভির নাম</label>
				    @if ($errors->has('name'))
                        <span class="help-block">
                            <strong style="color: red;">{{ $errors->first('name') }}</strong>
                        </span>
                    @endif
				    <input type="text" name="name" class="form-control" id="youTubeName" placeholder="মুভির নাম">
				  </div>
				  <div class="form-group">
				    <label for="youTubeDescription">মুভির বর্ননা</label>
				    <textarea name="description" id="editor" class="form-control" cols="30" rows="10"></textarea>
				  </div>
				    <div class="form-group{{ $errors->has('catagory') ? ' has-error' : '' }}">
				      <label for="catagory">ক‍্যাটাগরি</label>
					    @if ($errors->has('catagory'))
	                        <span class="help-block">
	                            <strong style="color: red;">{{ $errors->first('catagory') }}</strong>
	                        </span>
	                    @endif
				      <select id="catagory" class="form-control" name="catagory">
				        <option selected>পছন্দ করুন মুভির ক‍্যাটাগরি</option>
				        <option value="1">বাংলা</option>
				        <option value="2">হিন্দি</option>
				        <option value="3">ইংরেজি</option>
				        <option value="4">তামিল</option>
				        <option value="5">তেলেগু</option>
				      </select>
				    </div>
				  <button type="submit" class="btn btn-primary">নতুন মুভি</button>
				</form>
			</div>
		</div>
		<div class="col-md-6">
			<h6>ব‍্যবহার বিধি</h6>
			<hr>
			<ul>
				<li class="mb-2">ইউটিউব URL ব‍্যবহার করার জন‍্য পুরো URL ব‍্যবহার না করে শুধু মাত্র <kbd>watch?v=</kbd> এর পর যে অংশটুকু আছে তা ব‍্যবহার করুন। উদাহরন স্বরুপ লাল রং করা অংশটুকুই ব‍্যবহার করুন। https://www.youtube.com/watch?v=<span style="color: red;">DzBa71rNJ5YM</span></li>
				<li class="mb-2">মুভির নাম ইংরেজিতে অথবা বাংলাতে লিখুন।</li>
				<li class="mb-2">মুভির বর্ণনা এর ফিল্ডে মুভি সম্পর্কে আপনার মতামত অথবা বর্ণনা লিখুন, এটা আবশ‍্যিক নয়।</li>
				<li class="mb-2">ক‍্যাটাগরি ফিন্ডে মুভিটা কোন ভাষায় তা সিলেট করুন।</li>
			</ul>
		</div>
	</div>
</div>
@endsection

@section('footer-script')
<script src="{{ asset("js/ckeditor.js") }}"></script>

<script>
    ClassicEditor
        .create( document.querySelector( '#editor' ) )
        .catch( error => {
            console.error( error );
        } );
</script>
@endsection

movie-tube/youtubemovie/resources/views/video/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-9 col-sm-6">
            <div class="video-show">
                <iframe width="100%" height="500" src="{{ $video->url }}" frameborder="0" allowfullscreen></iframe>
            </div>
        </div>
        <div class="col-md-3 col-sm-6">
            <h6>নতুন মুভি</h6>
            <hr>
            @foreach($newmovies as $movie)
            <div class="video-show">
                <iframe width="100%" height="105" src="{{ $movie->url }}" frameborder="0" allowfullscreen></iframe>
                <p><a href="{{ route('video.show', $movie->id) }}">{{ $movie->name }}</a></p>
            </div>
            @endforeach
        </div>
    </div>
    <h4 class="mt-3">{{ $video->name }}</h4>
    <p>
        {!!html_entity_decode($video->description)!!}
    </p>
    <hr>
    <div class="row">
        <div class="col">
            <div class="fb-comments" data-href="http://movie-tube.tk/video/{{ $video->id }}" data-numposts="10"></div>
        </div>
        
        <div class="col">
        @auth    
            <p><strong>রেটিংঃ</strong> <span>@if(isset($rate)) আপনি <span class="bn">{{ $rate->rate }}</span> রেটিং দিয়েছেন, পরিবর্তন করুন @else মুভিটির রেটিং দিন @endif</span> </p> 
            <form action="{{ route('rate.store') }}" method="post">
            {{ csrf_field() }}
            <input type="text" name="video_id" value="{{ $video->id }}" hidden>
            <div class="form-check form-check-inline">
              <label class="form-check-label">
                <input class="form-check-input" type="radio" name="rate" id="inlineRadio1" value="2" checked> ২
              </label>
            </div>
            <div class="form-check form-check-inline">
              <label class="form-check-label">
                <input class="form-check-input" type="radio" name="rate" id="inlineRadio2" value="4"> ৪
              </label>
            </div>
            <div class="form-check form-check-inline">
              <label class="form-check-label">
                <input class="form-check-input" type="radio" name="rate" id="inlineRadio1" value="6"> ৬
              </label>
            </div>
            <div class="form-check form-check-inline">
              <label class="form-check-label">
                <input class="form-check-input" type="radio" name="rate" id="inlineRadio2" value="8"> ৮
              </label>
            </div>
            <div class="form-check form-check-inline">
              <label class="form-check-label">
                <input class="form-check-input" type="radio" name="rate" id="inlineRadio1" value="10"> ১০
              </label>
            </div>
            <div class="form-check form-check-inline">
              <label class="form-check-label">
                <button type="submit" class="btn btn-light btn-sm">রেটিং</button>
              </label>
            </div>
            </form>
            <hr>
        @endauth
        <div class="fb-share-button" data-href="http://movie-tube.tk/video/{{ $video->id }}" data-layout="button_count" data-size="large" data-mobile-iframe="true"><a class="fb-xfbml-parse-ignore" target="_blank" href="https://www.facebook.com/sharer/sharer.php?u=http%3A%2F%2Fmovie-tube.tk%2Fvideo%2F1&amp;src=sdkpreparse">Share</a></div>
        <hr>
        
        <div class="row">
            @foreach($viewrelative as $movie)
            <div class="col-md-6 col-sm-12">
                <div class="video-show">
                    <iframe width="100%" height="100" src="{{ $movie->url }}" frameborder="0" allowfullscreen></iframe>
                    <p><a href="{{ route('video.show', $movie->id) }}">{{ $movie->name }}</a></p>
                </div>
            </div>
            @endforeach
        </div>
        </div>
    </div>
</div>
@endsection