anirban/routes/web.php
<?php

use Illuminate\Support\Facades\Auth;

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();
Route::post('signin', 'Auth\SigninController@signin');
Route::post('signup', 'Auth\SignupController@signup');

Route::get('/home', 'HomeController@index')->name('home');

// Calendar
Route::get('calendar', 'CalendarController@index');

// Send SMS
Route::post('sms/sendsms', 'SendsmsController@sendsms');
Route::post('sms/sendlonesms', 'SendsmsController@sendlonesms');

// View User Only
Route::get('/dashboard/show/{account}', 'DashboardController@show')->name('dashboard.show');
Route::post('/dashboard/password', 'DashboardController@password')->name('dashboard.password');
Route::get('/dashboard', 'DashboardController@index')->name('dashboard');

// Member Route
Route::get('member/user/{user}', 'MemberController@active');
Route::post('member/profile/{profile}', 'MemberController@profile');
Route::resource('member', 'MemberController');

// Accounts Route
Route::get('account/lone/{account}', 'AccountController@active');
Route::resource('account', 'AccountController');

// Tasks Route
Route::get('task/user/{task}', 'TaskController@active');
Route::resource('task', 'TaskController');

// Others Route
Route::get('other/user/{other}', 'OtherController@active');
Route::resource('other', 'OtherController');

// Amounts Controller
Route::get('amount/details/{id}', 'AmountController@amountdetails');
Route::get('amount/daly/{account}', 'AmountController@amount');
Route::get('amount/saving/{account}', 'AmountController@saving');
Route::get('amount/dashboard', 'AmountController@dashboard');
Route::post('amount/daly', 'AmountController@dayamount');
Route::post('amount/transfer', 'AmountController@transfer');
Route::resource('amount', 'AmountController');

//Saving Route
Route::get('saving', 'SavingController@index');

// Lone Route
Route::get('lone', 'LoneController@index');
Route::get('lone/{id}', 'LoneController@show');
Route::post('lone/amount', 'LoneController@amount');
Route::post('lone/fixed', 'LoneController@fixed');

// Fixed Route
Route::get('fixed', 'FixedController@index');

// Role Route
Route::post('role/savepermission', 'RoleController@savepermission');
Route::get('role/add', 'RoleController@add');
Route::resource('role', 'RoleController');

// Permission Route
Route::resource('permission', 'PermissionController');

// Invoice Controller
Route::get('invoic/account-info/{account}', 'InvoiceController@accountinfo');
Route::get('invoic/account-info/print/{account}', 'InvoiceController@accountinfoprint');
Route::get('invoic/account-form/{account}', 'InvoiceController@accountform');

// Mobile
Route::get('/mobile/login', function () {
	if (Auth::check()) {
		return redirect('mobile/dashboard');
	} else {
    	return view('mobile.login');
	}
});
Route::get('mobile/dashboard', 'MobileController@dashboard');
Route::get('mobile/lone', 'MobileController@lone');
Route::get('mobile/saving', 'MobileController@saving');
Route::get('mobile/fixed', 'MobileController@fixed');
Route::get('mobile/show/{id}', 'MobileController@show');
Route::get('mobile/payment/{id}', 'MobileController@payment');
Route::post('mobile/login', 'MobileController@login');

anirban/app/Http/Controllers/MemberController.php
<?php

namespace App\Http\Controllers;

use App\Profile;
use App\Role;
use App\User;
use Illuminate\Http\Request;
use MercurySeries\Flashy\Flashy;

class MemberController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::all();
        return view('member.index', compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('member.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required|string|max:255',
            'email' => 'required|string|email|max:255|unique:users',
            'password' => 'required|string|min:6|confirmed',
        ]);

        $user = new User;
        $user->name = $request->name;
        $user->email = $request->email;
        $user->active = 0;
        $user->password = bcrypt($request->password);
        $user->save();

        $user->roles()->sync(4);

        $profile = new Profile;
        $profile->user()->associate($user);
        $profile->anirban_code = 'anirban_'.$user->id;
        $profile->save();
        Flashy::message('Success', 'http://your-awesome-link.com');
        return back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $profile = Profile::where('user_id', $id)->first();

        return view('member.show', compact('profile'));
    }

    public function profile(Request $request, Profile $profile)
    {
        if ($request->hasFile('photo')) {
            $imageName = $request->photo->store('public/users');
            $profile->photo = $imageName;
        }
        $profile->date_of_birth = $request->date_of_birth;
        $profile->father_name = $request->father_name;
        $profile->mother_name = $request->mother_name;
        $profile->date_of_joining = $request->date_of_joining;
        $profile->contact_number = $request->contact_number;
        $profile->alternate_contact_number = $request->alternate_contact_number;
        $profile->present_address = $request->present_address;
        $profile->permanent_address = $request->permanent_address;
        $profile->facebook_link = $request->facebook_link;
        $profile->save();
        Flashy::message('Success', 'http://your-awesome-link.com');
        return back();
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = User::find($id);
        $roles = Role::all();
        return view('member.edit', compact('user', 'roles'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'name' => 'required|string|max:255',
        ]);

        $user = User::find($id);
        $user->name = $request->name;
        $user->password = bcrypt($request->password);
        $user->save();
        $user->roles()->sync($request->role);
        Flashy::message('Success', 'http://your-awesome-link.com');
        return back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user = User::find($id);
        $user->delete();
        Flashy::message('Success', 'http://your-awesome-link.com');
        return back();
    }

    public function active(User $user)
    {
        if($user->active == 1){ $active = 0; }
        if($user->active == 0){ $active = 1; }

        $user->active = $active;
        $user->save();
        Flashy::message('Success', 'http://your-awesome-link.com');
        return redirect()->back();
    }
}

anirban/resources/views/member/create.blade.php
@extends('layouts.app')

@section('title', 'Member Create')
@section('content-title', 'সদস‍্য যুক্ত করুন')
@section('content-subtitle', 'সমিতিতে নতুন সদস‍্য যুক্ত করুন')
@section('link-list')
<li><a href="{{ route('home') }}"><i class="fa fa-dashboard"></i> ডেসবোর্ড</a></li>
<li ><a href="{{ route('member.index') }}">সদস‍্য সমূহ</a></li>
<li class="active"><a href="{{ route('member.create') }}">নতুন সদস‍্য যুক্ত করুন</a></li>
@endsection

@section('content')
@can('users.create')
<!-- Main content -->
<section class="content">

  <!-- Default box -->
  <div class="row">
    <div class="col-md-6">
      <div class="box box-primary">
        <div class="box-header with-border">
          <h3 class="box-title">নতুন সদস‍্য যুক্ত করুন</h3>
        </div>
        @include('layouts.message')
        <!-- /.box-header -->
        <!-- form start -->
        <form role="form" action="{{ route('member.store') }}" method="post">
          {{ csrf_field() }}
          <div class="box-body">
            <div class="form-group">
              <label for="name">সদস‍্য নাম</label>
              <input class="form-control" id="name" placeholder="Full Name" type="name" name="name" value="{{ old('name') }}">
            </div>
            <div class="form-group">
              <label for="exampleInputEmail1">ইমেল এড্রেস</label>
              <input class="form-control" id="exampleInputEmail1" placeholder="Enter email" type="email" name="email" value="{{ old('email') }}">
            </div>
            <div class="form-group">
              <label for="exampleInputPassword1">পাসওয়ার্ড</label>
              <input class="form-control" id="exampleInputPassword1" placeholder="Password" type="password" name="password">
            </div>
            <div class="form-group">
              <label for="password_confirmation">পুণরায় পাসওয়ার্ড</label>
              <input class="form-control" id="password_confirmation" placeholder="Retype Password" type="password" name="password_confirmation">
            </div>
          </div>
          <!-- /.box-body -->

          <div class="box-footer">
            <button type="submit" class="btn btn-primary">নতুন সদস‍্য যুক্ত করুন</button>
          </div>
        </form>
      </div>
    </div>
    <div class="col-md-6">
      <div class="box box-primary">
        <div class="box-header with-border">
          <h3 class="box-title">ব‍্যবহার বিধি</h3>
        </div>
        <!-- /.box-header -->
        <!-- form start -->
          <div class="box-body">
            
          </div>
          <!-- /.box-body -->
          <div class="box-footer">
            
          </div>
      </div>
    </div>
  </div>
  <!-- /.box -->
</section>
<!-- /.content -->
@endcan
@endsection

anirban/resources/views/member/edit.blade.php
@extends('layouts.app')

@section('title', 'Member Edit')
@section('content-title', 'সদস‍্য আপডেট পেজ')
@section('content-subtitle', 'সমিতির সদস‍্য ইনফরমেশন আপডেট করুন')
@section('link-list')
<li><a href="{{ route('home') }}"><i class="fa fa-dashboard"></i> ডেসবোর্ড</a></li>
<li ><a href="{{ route('member.index') }}">সদস‍্য সমূহ</a></li>
<li class="active"><a href="#">সদস‍্য আপডেট</a></li>
@endsection

@section('content')
@can('users.update')
<!-- Main content -->
<section class="content">

  <!-- Default box -->
  <div class="row">
    <div class="col-md-6">
      <div class="box box-primary">
        <div class="box-header with-border">
          <h3 class="box-title">সদস‍্য আপডেট</h3>
        </div>
        @include('layouts.message')
        <!-- /.box-header -->
        <!-- form start -->
        <form role="form" action="{{ route('member.update', $user->id) }}" method="post">
          {{ csrf_field() }}
          {{ method_field('PATCH') }}
          <div class="box-body">
            <div class="form-group">
              <label for="name">নাম</label>
              <input class="form-control" id="name" placeholder="Full Name" type="name" name="name" value="{{ $user->name }}">
            </div>
            <div class="form-group">
              <label for="exampleInputEmail1">ইমেল এড্রেস</label>
              <input class="form-control" id="exampleInputEmail1" placeholder="Enter email" type="email" name="email" value="{{ $user->email }}" disabled>
            </div>
            <div class="form-group">
              <label for="exampleInputPassword1">পাসওয়ার্ড</label>
              <input class="form-control" id="exampleInputPassword1" placeholder="Password" type="password" name="password">
            </div>
            <div class="form-group">
              <label for="password_confirmation">পুনরায় পাসওয়ার্ড</label>
              <input class="form-control" id="password_confirmation" placeholder="Retype Password" type="password" name="password_confirmation">
            </div>
            <div class="row">
              @foreach($roles as $role)
              <div class="col-md-3">
                <div class="checkbox">
                  <label>
                    <input type="checkbox" value="{{ $role->id }}" name="role[]" 
                    @foreach($user->roles as $user_role)
                      @if($user_role->id == $role->id) checked @endif
                    @endforeach
                    > {{ $role->name }}
                  </label>
                </div>
              </div>
              @endforeach
            </div>
          </div>
          <!-- /.box-body -->

          <div class="box-footer">
            <button type="submit" class="btn btn-primary">আপডেট করুন</button>
            <a href="{{ route('home') }}" class="btn btn-default pull-right">Back</a>
          </div>
        </form>
      </div>
    </div>
    <div class="col-md-6">
      <div class="box box-primary">
        <div class="box-header with-border">
          <h3 class="box-title">ব‍্যবহার বিধি</h3>
        </div>
        <!-- /.box-header -->
        <!-- form start -->
          <div class="box-body">
            
          </div>
          <!-- /.box-body -->
          <div class="box-footer">
            
          </div>
      </div>
    </div>
  </div>
  <!-- /.box -->
</section>
<!-- /.content -->
@endcan
@endsection

anirban/resources/views/member/index.blade.php
@extends('layouts.app')

@section('title', 'Member page')
@section('content-title', 'সদস‍্য সমূহ')
@section('content-subtitle', 'সমিতির সকল সদস‍্য সমূহ')
@section('link-list')
<li><a href="{{ route('home') }}"><i class="fa fa-dashboard"></i> ডেসবোর্ড</a></li>
<li class="active"><a href="{{ route('member.index') }}">সদস‍্য সমূহ</a></li>
@endsection

@section('header-script')
<link rel="stylesheet" href={{ asset("admin/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css") }}>
@endsection

@section('content')
@can('users.view')
<!-- Main content -->
<section class="content">

  <!-- Default box -->
  <div class="box">
    <div class="box-header">
      {{-- <h3 class="box-title">Data Table With Full Features</h3> --}}
    </div>
    <!-- /.box-header -->
    <div class="box-body">
      <table id="example1" class="table table-bordered table-striped">
        <thead>
          <tr>
            <th>সদস‍্য নাম</th>
            <th>ইমেল</th>
            <th>সদস‍্য কোড</th>
            <th>মোবাইল</th>
            <th>যোগদানের তারিখ</th>
            <th>স্টাটার্স</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          @foreach($users as $user)
          <tr>
            <td>{{ $user->name }}</td>
            <td>{{ $user->email }}</td>
            <td>{{ $user->profile->anirban_code }}</td>
            <td>{{ $user->profile->contact_number }}</td>
            <td>{{ $user->profile->date_of_joining }}</td>
            <td><a href="@can('users.create') {{ url('member/user', $user->id) }} @endcan">
              @if($user->active == 1) 
                <span class="fa fa-check"> একটিভ</span>
              @elseif($user->active == 0)
                <span class="fa fa-ban" style="color: red"> ডিএকটিভ</span>
              @endif
            </a></td>
            <td>
              <a href="{{ route('member.show', $user->id) }}" class="btn btn-success btn-xs"><span class="fa fa-user"></span></a>
              @can('users.update')
              <a href="{{ route('member.edit', $user->id) }}" class="btn btn-info btn-xs"><span class="fa fa-edit"></span></a>
              @endcan
              @can('users.delete')
              <form id="delete-form-{{ $user->id }}" method="post" action="{{ route('member.destroy',$user->id) }}" style="display: none">
                {{ csrf_field() }}
                {{ method_field('DELETE') }}
              </form>
              <a class="btn btn-danger btn-xs" href="" onclick="
              if(confirm('Are you sure, You Want to delete this?'))
                  {
                    event.preventDefault();
                    document.getElementById('delete-form-{{ $user->id }}').submit();
                  }
                  else{
                    event.preventDefault();
                  }" ><span class="fa fa-trash"></span></a>
             @endcan     
            </td>
          </tr>
          @endforeach
        </tbody>
        <tfoot>
          <tr>
            <th>সদস‍্য নাম</th>
            <th>ইমেল</th>
            <th>সদস‍্য কোড</th>
            <th>মোবাইল</th>
            <th>যোগদানের তারিখ</th>
            <th>স্টাটার্স</th>
            <th></th>
          </tr>
        </tfoot>
      </table>
    </div>
    <!-- /.box-body -->
  </div>
  <!-- /.box -->
</section>
<!-- /.content -->
@endcan
@endsection

@section('footer-script')
<script src={{ asset("admin/bower_components/datatables.net/js/jquery.dataTables.min.js") }}></script>
<script src={{ asset("admin/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js") }}></script>
<script>
  $(function () {
    $('#example1').DataTable()
  })
</script>
@endsection

anirban/resources/views/member/show.blade.php
@extends('layouts.app')

@section('header-script')
<link rel="stylesheet" href={{ asset("admin/bower_components/bootstrap-daterangepicker/daterangepicker.css") }}>
<link rel="stylesheet" href={{ asset("admin/bower_components/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css") }}>
@endsection

@section('title', 'প্রফাইল')
@section('content-title', 'প্রফাইল')
@section('content-subtitle', 'প্রফাইল সম্পাদন')
@section('link-list')
<li><a href="{{ route('home') }}"><i class="fa fa-dashboard"></i> ডেসবোর্ড</a></li>
<li ><a href="{{ route('member.index') }}">সদস‍্য লিস্ট</a></li>
<li class="active"><a href="#">প্রফাইল</a></li>
@endsection

@section('content')
@can('users.view', Auth::user())
<!-- Main content -->
<section class="content">

  <div class="row">
        <div class="col-md-3">

          <!-- Profile Image -->
          <div class="box box-primary">
            <div class="box-body box-profile">
              @if(empty($profile->photo))  
                <img class="profile-user-img img-responsive img-circle" src={{ asset("admin/dist/img/avatar04.png") }} alt="User profile picture">
              @else
                <img class="profile-user-img img-responsive img-circle" src="{{-- {{ Storage::url($profile->photo) }} --}} {{ asset($profile->photo) }}" alt="User profile picture" style="width: 100px; height: 100px;">
              @endif
              

              <h3 class="profile-username text-center">{{ $profile->user->name }}</h3>

              <p class="text-muted text-center">Email: {{ $profile->user->email }}</p>

              {{-- <ul class="list-group list-group-unbordered">
                <li class="list-group-item">
                  <b>Followers</b> <a class="pull-right">1,322</a>
                </li>
                <li class="list-group-item">
                  <b>Following</b> <a class="pull-right">543</a>
                </li>
                <li class="list-group-item">
                  <b>Friends</b> <a class="pull-right">13,287</a>
                </li>
              </ul> --}}

              {{-- <a href="#" class="btn btn-primary btn-block"><b>Follow</b></a> --}}
            </div>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->
        </div>
        <!-- /.col -->
        <div class="col-md-9">
          <div class="box box-info">
            <div class="box-header with-border">
              <h3 class="box-title">প্রফাইল</h3>
            </div>
            <!-- /.box-header -->
            <!-- form start -->
            
            <form class="form-horizontal" @can('users.view', Auth::user()) action="{{ url('member/profile', $profile->id) }}" method="post" @endcan enctype="multipart/form-data">
             @can('users.create', Auth::user()) {{ csrf_field() }} @endcan
             
              <div class="box-body">

                <div class="form-group">
                  <label for="father_name" class="col-sm-3 control-label">বাবার নাম</label>
                  <div class="col-sm-9">
                    <input type="text" class="form-control" id="father_name" placeholder="Father Name" name="father_name" value="{{ $profile->father_name }}">
                  </div>
                </div>

                <div class="form-group">
                  <label for="mother_name" class="col-sm-3 control-label">মার নাম</label>
                  <div class="col-sm-9">
                    <input type="text" class="form-control" id="mother_name" placeholder="Mother Name" name="mother_name" value="{{ $profile->mother_name }}">
                  </div>
                </div>

                <div class="form-group">
                  <label for="contact_number" class="col-sm-3 control-label">যোগাযোগ নম্বর</label>
                  <div class="col-sm-9">
                    <input type="text" class="form-control" id="contact_number" placeholder="Contact Number" name="contact_number" value="{{ $profile->contact_number }}">
                  </div>
                </div>

                <div class="form-group">
                  <label for="alternate_contact_number" class="col-sm-3 control-label">যোগাযোগ নম্বর</label>
                  <div class="col-sm-9">
                    <input type="text" class="form-control" id="alternate_contact_number" placeholder="Alternate Contact Number" name="alternate_contact_number" value="{{ $profile->alternate_contact_number }}">
                  </div>
                </div>

                <div class="form-group">
                  <label for="inputPassword3" class="col-sm-3 control-label">জন্মদিন</label>
                  <div class="col-sm-9">
                    <div class="input-group date">
                      <div class="input-group-addon">
                        <i class="fa fa-calendar"></i>
                      </div>
                      <input type="text" class="form-control pull-right" id="datepicker" name="date_of_birth" value="{{ $profile->date_of_birth }}" data-date-format="yyyy/mm/dd">
                    </div>
                  </div>
                </div>

                <div class="form-group">
                  <label for="inputPassword3" class="col-sm-3 control-label">যোগদানের তারিখ</label>
                  <div class="col-sm-9">
                    <div class="input-group date">
                      <div class="input-group-addon">
                        <i class="fa fa-calendar"></i>
                      </div>
                      <input type="text" class="form-control pull-right" id="datepicker1" name="date_of_joining" value="{{ $profile->date_of_joining }}" data-date-format="yyyy/mm/dd">
                    </div>
                  </div>
                </div>

                <div class="form-group">
                  <label for="contact_number" class="col-sm-3 control-label">বর্তমান ঠিকানা</label>
                  <div class="col-sm-9">
                    <textarea type="text" class="form-control" id="contact_number" placeholder="Present Address" name="present_address">{{ $profile->present_address }}</textarea>
                  </div>
                </div>

                <div class="form-group">
                  <label for="contact_number" class="col-sm-3 control-label">স্থায়ী ঠিকানা</label>
                  <div class="col-sm-9">
                    <textarea type="text" class="form-control" id="contact_number" placeholder="Present Address" name="permanent_address">{{ $profile->permanent_address }}</textarea>
                  </div>
                </div>

                <div class="form-group">
                  <label for="contact_number" class="col-sm-3 control-label">ফেসবুক আইডি</label>
                  <div class="col-sm-9">
                    <input type="text" class="form-control" id="contact_number" placeholder="facebook Id" name="facebook_link" value="{{ $profile->facebook_link }}">
                  </div>
                </div>

                <div class="form-group">
                  <label for="contact_number" class="col-sm-3 control-label">ছবি</label>
                  <div class="col-sm-9">
                    <input type="file" id="exampleInputFile" name="photo">
                  </div>
                </div>

              </div>
              <!-- /.box-body -->
              @can('users.view', Auth::user())
              <div class="box-footer">
                <button type="submit" class="btn btn-info pull-right">প্রফাইল আপডেট</button>
              </div>
              @endcan
              <!-- /.box-footer -->
            </form>
          </div>
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->

</section>
<!-- /.content -->
@endcan
@endsection

@section('footer-script')
<script src={{ asset("admin/bower_components/moment/min/moment.min.js") }}></script>
<script src={{ asset("admin/bower_components/bootstrap-daterangepicker/daterangepicker.js") }}></script>
<!-- bootstrap datepicker -->
<script src={{ asset("admin/bower_components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js") }}></script>

<script>
  $(function () {

    //Date picker
    $('#datepicker').datepicker({
      autoclose: true
    })
    $('#datepicker1').datepicker({
      autoclose: true
    })
  })
</script>
@endsection