anirban/routes/web.php
<?php

use Illuminate\Support\Facades\Auth;

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();
Route::post('signin', 'Auth\SigninController@signin');
Route::post('signup', 'Auth\SignupController@signup');

Route::get('/home', 'HomeController@index')->name('home');

// Calendar
Route::get('calendar', 'CalendarController@index');

// Send SMS
Route::post('sms/sendsms', 'SendsmsController@sendsms');
Route::post('sms/sendlonesms', 'SendsmsController@sendlonesms');

// View User Only
Route::get('/dashboard/show/{account}', 'DashboardController@show')->name('dashboard.show');
Route::post('/dashboard/password', 'DashboardController@password')->name('dashboard.password');
Route::get('/dashboard', 'DashboardController@index')->name('dashboard');

// Member Route
Route::get('member/user/{user}', 'MemberController@active');
Route::post('member/profile/{profile}', 'MemberController@profile');
Route::resource('member', 'MemberController');

// Accounts Route
Route::get('account/lone/{account}', 'AccountController@active');
Route::resource('account', 'AccountController');

// Tasks Route
Route::get('task/user/{task}', 'TaskController@active');
Route::resource('task', 'TaskController');

// Others Route
Route::get('other/user/{other}', 'OtherController@active');
Route::resource('other', 'OtherController');

// Amounts Controller
Route::get('amount/details/{id}', 'AmountController@amountdetails');
Route::get('amount/daly/{account}', 'AmountController@amount');
Route::get('amount/saving/{account}', 'AmountController@saving');
Route::get('amount/dashboard', 'AmountController@dashboard');
Route::post('amount/daly', 'AmountController@dayamount');
Route::post('amount/transfer', 'AmountController@transfer');
Route::resource('amount', 'AmountController');

//Saving Route
Route::get('saving', 'SavingController@index');

// Lone Route
Route::get('lone', 'LoneController@index');
Route::get('lone/{id}', 'LoneController@show');
Route::post('lone/amount', 'LoneController@amount');
Route::post('lone/fixed', 'LoneController@fixed');

// Fixed Route
Route::get('fixed', 'FixedController@index');

// Role Route
Route::post('role/savepermission', 'RoleController@savepermission');
Route::get('role/add', 'RoleController@add');
Route::resource('role', 'RoleController');

// Permission Route
Route::resource('permission', 'PermissionController');

// Invoice Controller
Route::get('invoic/account-info/{account}', 'InvoiceController@accountinfo');
Route::get('invoic/account-info/print/{account}', 'InvoiceController@accountinfoprint');
Route::get('invoic/account-form/{account}', 'InvoiceController@accountform');

// Mobile
Route::get('/mobile/login', function () {
	if (Auth::check()) {
		return redirect('mobile/dashboard');
	} else {
    	return view('mobile.login');
	}
});
Route::get('mobile/dashboard', 'MobileController@dashboard');
Route::get('mobile/lone', 'MobileController@lone');
Route::get('mobile/saving', 'MobileController@saving');
Route::get('mobile/fixed', 'MobileController@fixed');
Route::get('mobile/show/{id}', 'MobileController@show');
Route::get('mobile/payment/{id}', 'MobileController@payment');
Route::post('mobile/login', 'MobileController@login');

anirban/app/Http/Controllers/FixedController.php
<?php

namespace App\Http\Controllers;

use App\Account;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class FixedController extends Controller
{
    public function index()
    {
    	// Total Saving Account
        $fixed_accounts = Account::select(
                    DB::raw('accounts.*, 
                        SUM(amounts.saving_amount) as amount_saving_amount,
                        SUM(amounts.lone_amount) as amount_lone_amount,
                        SUM(amounts.elevation_amount) as amount_elevation_amount,
                        SUM(amounts.bonus_amount) as amount_bonus_amount,
                        Count(amounts.amount_date) as amount_amount_date'
                    ))
                 ->leftJoin('amounts', 'amounts.account_id', '=', 'accounts.id')
                 ->groupBy('accounts.id')
                 ->where([
                    ['accounts.status', '=', '0'],
                    ['accounts.account_type', '=', '2'],
                ])->get(); 

    	return view('fixed.index', compact('fixed_accounts'));
    }
}

anirban/resources/views/fixed/index.blade.php
@extends('layouts.app')

@section('title', 'ঋন একাউন্ট')
@section('content-title', 'ঋন')
@section('content-subtitle', 'সকল ঋন সমূহ')
@section('link-list')
<li><a href="{{ route('home') }}"><i class="fa fa-dashboard"></i> ডেসবোর্ড</a></li>
<li class="active"><a href="{{ url('lone') }}">ঋণ</a></li>
@endsection


@section('content')
@can('accounts.view')
<!-- Main content -->
<section class="content">
  <div class="row">
    @foreach($fixed_accounts as $account)
    <div class="col-md-4">
      <div class="box box-widget widget-user-2">
        <!-- Add the bg color to the header using any of the bg-* classes -->
        <div class="widget-user-header {{ \App\Classes\Helper::getProgress($account->id) }}">
          <div class="widget-user-image">
            @if(isset($account->user->profile->photo))
            <img src={{ asset($account->user->profile->photo) }} alt="User Avatar" class="img-circle" style="width: 65px; height: 65px;">
            @else
            <img class="img-circle" src="/admin/dist/img/user7-128x128.jpg" alt="User Avatar">
            @endif
          </div>
          <!-- /.widget-user-image -->
          <h3 class="widget-user-username">{{ $account->user->name }}</h3>
          <h5 class="widget-user-desc">{{ \App\Classes\Helper::getLastAmountDate($account->id) }} / AAN-{{ $account->id }}</h5>
          <h5 class="widget-user-desc">
          <form action="{{ url('sms/sendsms') }}" method="post" style="display: inline-block;">
          {{ csrf_field() }}
          <input type="text" name="ac" value="AAN-{{ $account->id }}" hidden>
          <input type="text" name="user_id" value="{{ $account->user->id }}" hidden>
          <input type="text" name="kisty" value="{{ $account->amount_amount_date }}" hidden>
          <input type="text" name="amount" value="{{ ($account->amount_saving_amount + $account->amount_bonus_amount) - $account->amount_elevation_amount}}" hidden>
          <button type="submit" class="btn btn-default btn-xs"><i class="fa fa-send-o"></i> SMS</button>
          </form>
          </h5>
        
        </div>
        <div class="box-footer no-padding">
          <ul class="nav nav-stacked">
            <li><a href="{{ route('account.show', $account->id) }}">মোট কিস্তি <span class="pull-right"><strong>{{ ($account->day + $account->week +$account->month) }} - {{ $account->amount_amount_date }} = {{ ($account->day + $account->week +$account->month) - ($account->amount_amount_date) }}</strong></span></a></li>
            <li><a href="#">টাকা তুলেছেন <span class="pull-right"><strong>{{ \App\Classes\Helper::getNumber($account->amount_elevation_amount) }}</strong></span></a></li>
            <li><a href="#">জমা রেখেছেন <span class="pull-right"><strong>{{ \App\Classes\Helper::getNumber($account->amount_saving_amount) }}</strong></span></a></li>
            <li><a href="#">বোনাস পেয়েছেন <span class="pull-right"><strong>{{ $account->amount_bonus_amount }}</strong></span></a></li>
            <li>
              <form action="{{ url('lone/fixed') }}" method="post">
                {{ csrf_field() }}
                <input type="text" value="{{ $account->id }}" name="account_id" hidden>
                <input type="text" value="{{ \App\Classes\Helper::getNextAmountDate($account->id) }}" name="amount_date" hidden>
                <input type="text" value="{{ $account->saving_amount }}" name="saving_amount" hidden>
                <input type="text" value="{{ $account->lone_total_amount }}" name="lone_amount" hidden>
              <button class="btn btn-primary btn-block btn-flat" type="submit">জমাঃ {{ $account->lone_total_amount }} + {{ $account->saving_amount }} = {{ $account->lone_total_amount + $account->saving_amount }} </button>
              </form>
            </li>
          </ul>
        </div>
        <div class="progress xs">
          <div class="progress-bar progress-bar-green" style="width: {{ \App\Classes\Helper::lonePercentage($account->id) }}%"></div>
        </div>
      </div>
    </div>
    @endforeach
  </div>
</section>
<!-- /.content -->
@endcan
@endsection